name: Continuous Integration
on:
  push:
    paths:
      - Dockerfile
      - entrypoint.sh
    branches:
      - development
jobs:
  push-to-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: elgohr/Publish-Docker-Github-Action@v5
      name: Publish to Docker
      with:
        name: madfoat/kubecommands
        username: ${{ secrets.DH_UN_C }}
        password: ${{ secrets.DH_PS_C }}
        tags: latest,1.28.4
        cache: true